config/routes.rb
Rails.application.routes.draw do
  resources :users do
    get 'followers', on: :member
    get 'followings', on: :member
    post 'follow', on: :member
    delete 'unfollow', on: :member
  end
  resources :posts
  resource :sessions, only: [ :new, :create, :destroy ]
  root to:'root#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :from, class_name: "User"
  belongs_to :to, class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }


  def self.from_followed_users(user)
		where("user_id IN (SELECT to_id FROM followings WHERE from_id = :user_id) OR user_id = :user_id", user_id: user.id)
  end

end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts, dependent: :destroy
	has_many :out_followings, class_name: "Following", foreign_key: :from_id, dependent: :destroy
	has_many :followed_users, class_name: "User", through: :out_followings, source: :to
	has_many :in_followings, class_name: "Following", foreign_key: :to_id, dependent: :destroy
	has_many :followers, class_name: "User", through: :in_followings, source: :from
    has_secure_password
	validates :name, presence: true, length: { maximum: 30 }
	validates :email, format: { with: /\A[^@]+@[^@]+\z/ }, uniqueness: true
	before_save { self.email = email.downcase }
    before_save { self.session_token ||= Digest::SHA1.hexdigest(SecureRandom.urlsafe_base64.to_s) }


	def follow(user)
		out_followings.create(to_id: user.id)
	end
  
	def unfollow(user)
		following = out_followings.find_by(to_id: user.id)
		if following
			following.destroy
			true
		else
			false
		end
	end
  
	def following?(user)
		followed_users.exists?(user.id)
	end
  
	def followed_by?(user)
		followers.exists?(user.id)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  #before_action :authenticate_user
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  # def index
	#	@posts = Post.all
	#	@post = current_user.posts.build
  #end

  def index
	@posts = Post.from_followed_users(current_user).order("created_at DESC")
	@post = current_user.posts.build
  end

  def create
  	@post = current_user.posts.build(create_params)
  	if @post.save
  		flash[:success] = "Posted successfully"
  		redirect_to posts_path
  	else
  		render "new"
  	end
  end

  def destroy
  	@post = current_user.posts.find_by(id: params[:id])
  	if @post && @post.destroy
	  	flash[:success] = "Post deleted"
	  else
	  	flash[:error] = "Cannot delete post"
	  end
  	redirect_to posts_path
  end


  private

  def create_params
  	params.require(:post).permit(:content)
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def home

  end
  def Sandbox
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
				sign_in(@user)
        flash[:success] = "Welcome back, #{@user.name}!"
        redirect_to @user
    else
        flash.now[:error] = "Invalid email/password combination"
        render "new"
    end  	
  end
  
  def destroy
  	sign_out
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :followers, :followings, :follow, :unfollow]


  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @posts = @user.posts
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(create_params)
    if @user.save
      sign_in(@user)
      flash[:success] = "Welcome, #{@user.name}!"
      redirect_to @user
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
       if @user.update(update_params)
      redirect_to user_url(@user), notice: "用户信息已经成功更新." 
      else
      render :edit, status: :unprocessable_entity 
      end
     end

  # DELETE /users/1 or /users/1.json
  def destroy
       @user.destroy
      redirect_to users_url, notice: "用户已经成功删除."
  end

  def followers
    @users = @user.followers
    @title = "Followers"
    render "followings"
  end

  def followings
    @users = @user.followed_users
    @title = "Followed Users"
    render "followings"
  end

  def follow
    if current_user.follow(@user)
      flash[:success] = "You are following #{@user.name}"
    else
      flash[:error] = "Something went wrong.  You cannot follow #{@user.name}"
    end
    redirect_to @user
  end

  def unfollow
    if current_user.unfollow(@user)
      flash[:success] = "You are no longer following #{@user.name}"
    else
      flash[:error] = "Something went wrong.  You cannot unfollow #{@user.name}"
    end
    redirect_to @user
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def update_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def create_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def authenticate_user
    unless signed_in?
      flash[:notice] = "Please sign-in to continue"
      redirect_to new_sessions_path
    end
  end

  def sign_in(user)
      session[:session_token] = user.session_token
  end

  def signed_in?
      !current_user.nil?
  end

  def current_user
      @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def current_user?(user)
    current_user == user
  end

  def sign_out
  	@current_user = nil
  	session.delete(:session_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 75 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://cravatar.cn/avatar/#{gravatar_id}?s=#{options[:size]}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codecamp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>

<!-- New header -->
<header>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container-fluid">
<%= link_to "CodeCamp", root_path, class: "navbar-brand", id: "logo"%>

  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
        <% if signed_in? %>
      <li class="nav-item">
        <li><%= link_to "Users", users_path, class:"nav-link active" %></li>
      </li>
      <li class="nav-item">
          <li><%= link_to "Posts", posts_path, class:"nav-link" %></li>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= current_user.name %>
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", sessions_path, method: "delete" %>
                  </li>
        </ul>
      </li>
       <li>  
        <% end %>   
      </li>
    </ul>
  </div>
</div>
</nav>
</header>

<!-- Content wrapped in container -->
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>  
  <%= yield %>
 
  <!-- Debugging footer --><hr>
  <%= content_tag :div, debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<div class="row">
  <aside class="span4">
    <section>
    	<%= render "shared/user_info", user: current_user %>
    </section>
    <section>
        <%= form_for (Post.new) do |f| %>
	      <%= render "shared/form_errors", record: @post %>
        <%= f.text_area :content, placeholder: "Write a new post" %><br />
        <%= f.submit "Post", class: "btn btn-primary" %>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h1>Posts</h1>
    <ul class="posts">
      <%= render partial: "shared/post", collection: @posts %>
    </ul>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for (Post.new)  do |f| %>
   <%# render "shared/form_errors", record: @post %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/root/home.html.erb
<h1>Welcome to FirstApp</h1>
<center>
    <%= link_to "Sign-in", new_sessions_path, class: "btn btn-large btn-primary" %>    <br>
    <%= link_to "Register!", new_user_path %>  
</center>

app/views/shared/_form_errors.html.erb
<% if record.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(record.errors.count, "error") %> prohibited this <%= record.class.model_name.human %> from being saved:</h2>
    <ul>
    <% record.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_post.html.erb
<li class="post">
  <%= link_to gravatar_for(post.user), post.user, class: "gravatar" %>
  <%= link_to post.user.name, post.user, class: "user" %>
  <%= content_tag :span, post.content, class: "content" %>
  <%= content_tag :span, "Posted #{time_ago_in_words(post.created_at)} ago", class: "timestamp" %>
	<%= link_to "delete", post, class: "delete", method: :delete, confirm: "Are you sure?" if current_user?(post.user) %>          
</li>

app/views/shared/_user.html.erb
<li class="user">
  <%= link_to gravatar_for(user), user %>
  <%= link_to user.name, user %>
</li>

app/views/shared/_user_actions.html.erb
<% unless current_user?(@user) %>
  <% if current_user.following?(@user) %>
    <%= link_to "Unfollow", unfollow_user_path(@user), class: "btn btn-secondary btn-sm", method: :delete %>
  <% else %>
	  <%= button_to "Follow", follow_user_path(@user), class: "btn btn-primary btn-sm" %>
  <% end %>
<% end %>

app/views/shared/_user_info.html.erb
<h1>
  <%= gravatar_for user %>
  <%= user.name %>
</h1>
<%= pluralize user.posts.count, "posts" %><br>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
	<%= render "shared/form_errors", record: @user %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, disabled: true %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>  
  </div>
  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/followings.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <%= render "shared/user_info", user: @user %>
    </section>
    <section>
      <%= render "shared/user_actions", user: @user %>
    </section>
  </aside>
  <div class="span8">
    <h1><%= @title %></h1>
    <ul class="users">
      <%= render partial: "shared/user", collection: @users %>
    </ul>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<div class="container">
  <ul class="users">
    <%= render partial: "shared/user", collection: @users %>
  </ul>
</div>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_for(@user) do |f| %>
	<%= render "shared/form_errors", record: @user %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>  
  </div>
  <div class="actions">
    <%= f.submit "Register!", class: "btn btn-primary" %>
  </div>
<% end %>

    

app/views/users/show.html.erb
<div class="row">
  <aside class="span4">
    <section>
    	<%= render "shared/user_info", user: @user %>
    </section>
   	<section>
   		<%= render "shared/user_actions", user: @user %>
    </section>
  </aside>
 <div class="span8">
    <h1>Posts</h1>
    <ul class="posts">
      <%= render partial: "shared/post", collection: @posts %>
    </ul>
  </div>
</div>